Let's try some basic tests of `VB.jl`:

In [1]:
include("VB.jl")
using VB
using Distributions

Let's try to make a Gaussian node with several different sizes and parameterizations:

In [2]:
ndims = (5, 5)  # node dimensions
vardims = 3  # dimension of variable

3

In [3]:
μ = Array{Vector{Float64}}(ndims)
Σ = Array{Matrix{Float64}}(ndims)

for idx in eachindex(μ)
    μ[idx] = rand(vardims)
end

for idx in eachindex(Σ)
    C = rand(vardims, vardims)
    Σ[idx] = C * C'
end

In [4]:
μ[1]

3-element Array{Float64,1}:
 0.876951
 0.246102
 0.170345

In [5]:
Σ[1]

3x3 Array{Float64,2}:
 0.11082   0.313655  0.13769 
 0.313655  1.47799   0.863618
 0.13769   0.863618  0.567495

In [6]:
det(Σ[2])

0.003663163183413293

In [7]:
pars = (μ, Σ)
aa = map(MultivariateNormal, pars...)

5x5 Array{Distributions.MvNormal{PDMats.PDMat,Array{Float64,1}},2}:
 FullNormal(
dim: 3
μ: [0.8769514067157775,0.24610182410180603,0.17034472341320228]
Σ: 3x3 Array{Float64,2}:
 0.11082   0.313655  0.13769 
 0.313655  1.47799   0.863618
 0.13769   0.863618  0.567495
)
   …  FullNormal(
dim: 3
μ: [0.14054895334245132,0.5344265758469189,0.5236294477024335]
Σ: 3x3 Array{Float64,2}:
 0.87475  1.09703  1.00861
 1.09703  1.65314  1.07342
 1.00861  1.07342  1.29564
)
                
 FullNormal(
dim: 3
μ: [0.2578569633176675,0.5168009987733992,0.10258019147309838]
Σ: 3x3 Array{Float64,2}:
 1.76268  1.96304  1.98282
 1.96304  2.21833  2.24754
 1.98282  2.24754  2.3432 
)
                FullNormal(
dim: 3
μ: [0.06223556338032199,0.3050166982764879,0.6431749444853827]
Σ: 3x3 Array{Float64,2}:
 1.71214  1.03858   1.09902 
 1.03858  0.857874  0.761257
 1.09902  0.761257  0.941897
)
          
 FullNormal(
dim: 3
μ: [0.49382316987651187,0.9139222205703994,0.15847265988555437]
Σ: 3x3 Array{Float64

In [8]:
rr = RandomNode(aa, Factor[]);

In [9]:
typeof(aa)

Array{Distributions.MvNormal{PDMats.PDMat,Array{Float64,1}},2}

In [10]:
typeof(aa) <: AbstractArray{typeof(aa[1]), 2}

true

In [11]:
ss = RandomNode(MultivariateNormal, pars...);

In [12]:
E(ss)

5x5 Array{Array{Float64,1},2}:
 [0.8769514067157775,0.24610182410180603,0.17034472341320228]   …  [0.14054895334245132,0.5344265758469189,0.5236294477024335] 
 [0.2578569633176675,0.5168009987733992,0.10258019147309838]       [0.06223556338032199,0.3050166982764879,0.6431749444853827] 
 [0.49382316987651187,0.9139222205703994,0.15847265988555437]      [0.9298564828706564,0.30809463360635125,0.29156221340511457]
 [0.19200739056107285,0.017806487114024883,0.5574408167418736]     [0.9642842274627401,0.39214466926153513,0.4271547176352064] 
 [0.9210975655648572,0.483853308771236,0.34637624608772777]        [0.7106397549752725,0.05252345917543333,0.7909222852785438] 

In [13]:
typeof(ss).parameters[1]

Distributions.MvNormal{PDMats.PDMat,Array{Float64,1}}

# Make a factor and check its value

In [14]:
μ = rand(10)
τ = rand(10)
x = RandomNode(Normal, rand(10), rand(10))
f = LogNormalFactor(x, μ, τ)

VB.LogNormalFactor(VB.RandomNode{Distributions.Normal,1}([Distributions.Normal(μ=0.341959405459622, σ=0.606879148847915),Distributions.Normal(μ=0.1850374718292518, σ=0.8437327026884118),Distributions.Normal(μ=0.10712656765468065, σ=0.2650652511792124),Distributions.Normal(μ=0.8663521378621362, σ=0.6705701026184843),Distributions.Normal(μ=0.7065726120003488, σ=0.17087848630307745),Distributions.Normal(μ=0.0006678253967637993, σ=0.3246955078714904),Distributions.Normal(μ=0.8263261030449367, σ=0.838127521128402),Distributions.Normal(μ=0.5624636690699945, σ=0.23923320306551976),Distributions.Normal(μ=0.2392464009436892, σ=0.08704080613575349),Distributions.Normal(μ=0.09108875883746137, σ=0.7414352925757048)],VB.Factor[]),VB.ConstantNode{Float64,1}([0.014969247827551824,0.18917567687512205,0.974081344659411,0.27854296371745635,0.20247636612269293,0.48785482298274907,0.2579793148669802,0.37656250049370477,0.00046455313810178644,0.7418800594226185],VB.Factor[]),VB.ConstantNode{Float64,1}([0.4

In [15]:
value(f)

-6.356565480041587

In [16]:
register(f)
x.factors[1]

VB.LogNormalFactor(VB.RandomNode{Distributions.Normal,1}([Distributions.Normal(μ=0.341959405459622, σ=0.606879148847915),Distributions.Normal(μ=0.1850374718292518, σ=0.8437327026884118),Distributions.Normal(μ=0.10712656765468065, σ=0.2650652511792124),Distributions.Normal(μ=0.8663521378621362, σ=0.6705701026184843),Distributions.Normal(μ=0.7065726120003488, σ=0.17087848630307745),Distributions.Normal(μ=0.0006678253967637993, σ=0.3246955078714904),Distributions.Normal(μ=0.8263261030449367, σ=0.838127521128402),Distributions.Normal(μ=0.5624636690699945, σ=0.23923320306551976),Distributions.Normal(μ=0.2392464009436892, σ=0.08704080613575349),Distributions.Normal(μ=0.09108875883746137, σ=0.7414352925757048)],VB.Factor[VB.LogNormalFactor(#= circular reference =#)]),VB.ConstantNode{Float64,1}([0.014969247827551824,0.18917567687512205,0.974081344659411,0.27854296371745635,0.20247636612269293,0.48785482298274907,0.2579793148669802,0.37656250049370477,0.00046455313810178644,0.7418800594226185],

In [17]:
g = EntropyFactor(x)
value(g)

4.553516797727002

In [18]:
naturals(x)

10-element Array{Tuple{Float64,Float64},1}:
 (0.9284747997682625,-1.3575804392926623)  
 (0.2599261182460372,-0.7023607588140063)  
 (1.5247252602149493,-7.1164665012411135)  
 (1.9266644251331773,-1.1119407114799376)  
 (24.198142110475167,-17.123606052298573)  
 (0.0063344712641442555,-4.742610340098126)
 (1.176335676900813,-0.7117865891965186)   
 (9.827692639062775,-8.73629105264023)     
 (31.579089493120556,-65.9970000981399)    
 (0.16569838478643087,-0.9095435424809267) 

# Let's make a simple model

We want a simple model of inference for a normal distribution:

$$
\begin{aligned}
    y \sim \mathcal{N}(\mu, \tau) \\
    \mu \sim \mathcal{N}(\mu_0, \tau_0) \\
    \tau \sim \mathrm{Ga}(\alpha, \beta) \\
    q(\mu) = \mathcal{N}(m, t) \\
    q(\tau) = \mathrm{Ga}(a, b)
\end{aligned}
$$

This model is conjugate, and can be solved by straightforward updates of the natural parameters of the posterior.

## Make the nodes

We need to make nodes for all the random variables that will need to be updated (we can also create nodes for parameter arrays, but these will be converted automatically if we don't).

In [19]:
dims = (5, 6)

# note: it won't matter much how we initialize here
μ = RandomNode(Normal, zeros(dims), ones(dims))
τ = RandomNode(Gamma, ones(dims), ones(dims))

y = rand(dims)

5x6 Array{Float64,2}:
 0.40263   0.958446  0.209475  0.769511  0.443911  0.469015
 0.810418  0.53836   0.966693  0.454408  0.219621  0.364902
 0.14952   0.688689  0.769968  0.686289  0.84506   0.615569
 0.42307   0.4824    0.857419  0.404556  0.304068  0.344346
 0.38416   0.956978  0.271889  0.296278  0.601463  0.939776

Now make factors: We need a Normal factor for the observation model plus a prior and an entropy for each node.

In [22]:
obs = LogNormalFactor(y, μ, τ)
μ_prior = LogNormalFactor(μ, zeros(dims), 2 * ones(dims))
τ_prior = LogGammaFactor(τ, 1.1 * ones(dims), ones(dims))

VB.LogGammaFactor(VB.RandomNode{Distributions.Gamma,2}(5x6 Array{Distributions.Gamma,2}:
 Distributions.Gamma(α=1.0, θ=1.0)  …  Distributions.Gamma(α=1.0, θ=1.0)
 Distributions.Gamma(α=1.0, θ=1.0)     Distributions.Gamma(α=1.0, θ=1.0)
 Distributions.Gamma(α=1.0, θ=1.0)     Distributions.Gamma(α=1.0, θ=1.0)
 Distributions.Gamma(α=1.0, θ=1.0)     Distributions.Gamma(α=1.0, θ=1.0)
 Distributions.Gamma(α=1.0, θ=1.0)     Distributions.Gamma(α=1.0, θ=1.0),VB.Factor[]),VB.ConstantNode{Float64,2}(5x6 Array{Float64,2}:
 1.1  1.1  1.1  1.1  1.1  1.1
 1.1  1.1  1.1  1.1  1.1  1.1
 1.1  1.1  1.1  1.1  1.1  1.1
 1.1  1.1  1.1  1.1  1.1  1.1
 1.1  1.1  1.1  1.1  1.1  1.1,VB.Factor[]),VB.ConstantNode{Float64,2}(5x6 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0,VB.Factor[]))

In [23]:
value(obs), value(μ_prior), value(τ_prior)

(-39.43387035146723,-67.96536370453937,7.496173237795199)